// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzcorhfkpxpkklhsdxqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Y29yaGZrcHhwa2tsaHNkeHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDQ4MDAsImV4cCI6MjA2NTkyMDgwMH0.1tMGbM-gySsreXfD3uTljd-hE3wqZvCx8mjldVFCTy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});